### ISSUE TITLE
[Bug]: Issue with vendor_prefixed folder and git

### ISSUE THREAD

**Issue by palicko** [QualityUnit/wp-urlslab#1407]
### Quick summary
When WP project uses git and this plugin is installed, git ignores folders in `vendor_prefixed`, because of `/*` line in `vendor_prefixed/.gitignore`. So when project is deployed to the server from git repo, those folders are missing and plugin throws fatal.

### Steps to reproduce *
1. Create WP project on localhost and initialize git.
2. Install plugin.
3. Add plugin files to git.
4. Deploy project to the dev server from git repository.
5. Activate plugin on the dev server.

### What you expected to happen *
Plugin should be activated.

### What actually happened *
Plugin throws because some files are missing from the repository
```
PHP Fatal error: Uncaught Error: Failed opening required '/wp-content/plugins/urlslab//vendor_prefixed/autoload.php' (include_path='.:/usr/share/php') in /wp-content/plugins/urlslab/includes/class-urlslab.php:324
```

---

#### Other notes

---

#### Reproducibility *
Consistent

**Comment by vzeman** [comment]
@palicko could you please run the command from: https://github.com/QualityUnit/wp-urlslab#dev-contribution 
```
bash ./.github/scripts/build-files-dev.sh
```

**Comment by palicko** [comment]
@vzeman plugin was downloaded right from the wordpress.org (with WP CLI), not from this github repository, so there are no build scripts.
So you're saying, that only way to use this plugin with git is to have additional build step (to download composer deps) in CI/CD?

**Comment by vzeman** [comment]
@palicko Thx for clarification, we are going to test `wp cli` deployment.
Until now all installations we did from marketplace or by uploading zip file.

**Comment by mvstepanek** [comment]
@palicko I performed several tests with WP CLI and could not reproduce your error. We discovered some new bugs, but none that were specific to your issue, unfortunately. Could you provide a copy of your stack? We can switch to email communication at `mstepanek@qualityunit.com`.

At present, we primarily use Composer to install plugin, and then we perform direct installations from wordpress.org, where the source code build is identical.

**Comment by palicko** [comment]
I think we don't get each other :)
Issue is not that plugin downloaded via WP CLI doesn't have those folders or is not working.

Issue is that when project is using git, `urlslab/vendor_prefixed/.gitignore`  is causing some necessary files from this plugin to not be included in project's git repo.

This is screenshot from fresh WP project, where I added your plugin downloaded from wordpress.org and initialised git with `git init`. Those greyed out ignored files/folders would not be included in the git repo for my project. So when my project is deployed to the dev/prod server from git repo, plugin wouldn't be working properly because it is missing those files in `vendor_prefixed/` folder.

<img width="381" alt="Screenshot 2023-11-16 at 22 51 35" src="https://github.com/QualityUnit/wp-urlslab/assets/4531209/a6a771ff-f4e7-46c8-a7ff-eda5c0c3ea09">

**Comment by mvstepanek** [comment]
I see. Please feel free to edit the `.gitignore` file. This is a specific issue related to your technology stack, which is incorrect as it stands. 

You should never commit plugins and WordPress like this; rather, install them via Composer during the build process before deployment. This is the correct method. The repository should contain only the necessary files that cannot be built or downloaded by Composer, etc.

We will enhance our code by removing `.gitignore` files from the built code to help similar technology stacks.

I would be delighted to assist with any special requirements or new ideas you might have. Additionally, we can offer you a complimentary introduction to the plugin, either online or in person in Bratislava. My email is provided above.

**Comment by palicko** [comment]
Okay, so I'll just edit `.gitignore` for now and watch out for the next update.

It would be nice to have the option to use plugin in this classic tech stack with Git. I get that it's not ideal, but I think most people usually don't want to use Composer and stacks like Bedrock on the most simple projects:)

Anyway, thanks for the quick response!
