### ISSUE TITLE
URLslab Plugin: url-relation API endpoint POST method not working

### ISSUE THREAD

**Issue by jremen** [QualityUnit/wp-urlslab#490]
In Related Resources table of URLslab Plugin (endpoint /wp-json/urlslab/v1/url-relation) POST method is not working.
No file can't be imported, no row can be modified.

Result:
`POST http://liveagent.local/wp-json/urlslab/v1/url-relation/18182370 404 (Not Found)`

Response:
`{code: "rest_no_route", message: "No route was found matching the URL and request method.",…}
code
: 
"rest_no_route"
data
: 
{status: 404}
message
: 
"No route was found matching the URL and request method."`

**Comment by vzeman** [comment]
```/import is working correctly as I see in my local installation``` 

or how can I simulate the bug?

Here is example of import file
[outputs-liveagentlocal.csv](https://github.com/QualityUnit/wp-urlslab/files/10933666/outputs-liveagentlocal.csv)

**Comment by vzeman** [comment]
in import you used wrong column names (they were changed in meantime)
